import type {Movie} from './types/Movie';

export const movies: Movie[] = [
  {
    id: 1,
    title: 'Dark Storm',
    image: '1.jpg',
    genre: 'drama',
    rating: 8.3,
    description:
      'A brooding tale of ambition and betrayal as a city braces for collapse. When a charismatic power broker rises from the shadows, long‑buried secrets resurface, fracturing alliances and igniting a chain of irreversible consequences. As political tensions erupt and trust becomes a rare commodity, the people trapped in the storm must choose between loyalty, survival, and truth.',
    actors: [
      'Lena Harwood',
      'Caleb Mercer',
      'Jonas Hale',
      'Vivian Cross',
      'Elias Renn',
      'Harper Lys',
    ],
  },
  {
    id: 2,
    title: 'Whisper of Fate',
    image: '2.jpg',
    genre: 'fantasy',
    rating: 7.7,
    description:
      "A young mage discovers a hidden prophecy that could reshape the future of her realm. As ancient forces awaken and the balance of magic begins to crack, she must venture across forbidden lands to confront a shadow stirring beneath the world's surface. Guided by unlikely allies and haunted by visions of a destiny she never asked for, she faces a choice that will determine the fate of all living realms.",
    actors: [
      'Elara Quinn',
      'Marek Thorne',
      'Sera Dawn',
      'Nolan Crest',
      'Ivy Solis',
      'Roran Vex',
    ],
  },
  {
    id: 3,
    title: 'Beyond the Edge',
    image: '3.jpg',
    genre: 'horror',
    rating: 6.3,
    description:
      'An expedition into a forgotten ruin unleashes horrors from another dimension. When the team uncovers an ancient seal carved with incomprehensible symbols, reality begins to warp around them. Their senses betray them, the walls whisper, and the boundary between their world and something far older grows increasingly thin. Survival means facing the truth that some doors were never meant to be opened.',
    actors: [
      'Iris Vale',
      'Damien Cross',
      'Tara Wynn',
      'Oren Gale',
      'Selene Ash',
      'Victor Rune',
    ],
  },
  {
    id: 4,
    title: 'Lost in Shadows',
    image: '4.jpg',
    genre: 'action',
    rating: 9.3,
    description:
      'A rogue operative races against time to stop a shadowy organization from triggering a global collapse. As she navigates a maze of double agents, encrypted intelligence, and deadly traps, the line between friend and foe becomes razor-thin. With the world on the brink, she must confront the ghosts of her past to dismantle a conspiracy built on deception and fear.',
    actors: [
      'Ryder Blaze',
      'Mila Hart',
      'Kai Draven',
      'Lucien Crow',
      'Asha Vale',
      'Dex Rowan',
    ],
  },
  {
    id: 5,
    title: 'Echoes of Power',
    image: '5.jpg',
    genre: 'fantasy',
    rating: 6.9,
    description:
      'Ancient magic awakens as two kingdoms clash for control of a sacred relic. As tensions rise and armies assemble, a hidden group of mystics holds the key to unlocking the relic’s true potential. The fate of the realm hinges on fragile alliances, mystical forces, and the courage of those willing to defy destiny.',
    actors: [
      'Elyra Stone',
      'Thane Merrick',
      'Owen Reed',
      'Liora Solen',
      'Garrick Thorn',
      'Sianne Vale',
    ],
  },
  {
    id: 6,
    title: 'Grim Reckoning',
    image: '6.jpg',
    genre: 'drama',
    rating: 8.4,
    description:
      'A determined detective confronts his own turbulent past while pursuing a criminal mastermind who seems to anticipate every move. As the investigation spirals into a deadly game of cat and mouse, he must face the growing realization that the truth behind the case is more personal—and more devastating—than he ever imagined.',
    actors: [
      'Viktor Hale',
      'Nadia Trent',
      'Leon Frost',
      'Marin Vale',
      'Silas Kade',
      'Jenna Crowe',
    ],
  },
  {
    id: 7,
    title: "Fury's Flight",
    image: '7.jpg',
    genre: 'action',
    rating: 9.8,
    description:
      'A fearless pilot fights to expose a global conspiracy threatening millions. After uncovering classified intel on an airborne weapons system, she becomes the target of elite mercenaries and corrupt officials. Against impossible odds, she takes to the skies for a showdown that will determine the safety of the world.',
    actors: [
      'Ava Kestrel',
      'Dante Rourke',
      'Silas Vorn',
      'Rhea Stone',
      'Kade Mercer',
      'Vesper Lyn',
    ],
  },
  {
    id: 8,
    title: 'Path of the Forgotten',
    image: '8.jpg',
    genre: 'action',
    rating: 7.2,
    description:
      "A former soldier must reclaim his identity while navigating a dangerous criminal underworld. As fragments of his memory return, he discovers he was part of a covert project with ties to the city's most feared syndicate. Every step draws him closer to a truth that threatens everything he knows.",
    actors: [
      'Marcus Vale',
      'Liora Finch',
      'Derek Shaw',
      'Harlan Wren',
      'Nova Crest',
      'Tyson Vorn',
    ],
  },
  {
    id: 9,
    title: "Nightmare's Threshold",
    image: '9.jpg',
    genre: 'horror',
    rating: 1.7,
    description:
      'A cursed mirror traps its victims within their darkest fears. When a group of friends accidentally unleashes the curse, they must confront illusions so vivid they blur with reality. The more they resist, the stronger the nightmare becomes, until escaping may require a sacrifice none are willing to make.',
    actors: [
      'Harper Gage',
      'Evan Cole',
      'Rhea Knox',
      'Mira Shade',
      'Jonas Kade',
      'Willow Thorn',
    ],
  },
  {
    id: 10,
    title: 'Eternal Hunt',
    image: '10.jpg',
    genre: 'fantasy',
    rating: 7.5,
    description:
      'A warrior is bound to an immortal beast in a quest to break an ancient curse. Their uneasy partnership forces them into hostile territories, mythical battlegrounds, and realms long forgotten by time. Along the way, they uncover the truth behind the curse—one rooted in betrayal, sacrifice, and a forgotten war.',
    actors: [
      'Kael Rowan',
      'Seren Vale',
      'Orin Dray',
      'Maelis Thorn',
      'Jorin Crest',
      'Alara Wynn',
    ],
  },
  {
    id: 11,
    title: 'Legacy of the Void',
    image: '11.jpg',
    genre: 'action',
    rating: 8.5,
    description:
      'A secret agent uncovers a weapon capable of erasing entire civilizations. As she races through war zones, encrypted networks, and hidden fortresses, she faces enemies determined to unleash chaos. Every revelation brings her closer to unraveling not only the weapon’s origin but also the truth about her own organization.',
    actors: [
      'Zane Cutter',
      'Elena Ward',
      'Jax Orion',
      'Nira Frost',
      'Callen Voss',
      'Lyra Vaughn',
    ],
  },
  {
    id: 12,
    title: "Shadow's Crescent",
    image: '12.jpg',
    genre: 'horror',
    rating: 7.5,
    description:
      'A lunar ritual awakens a supernatural threat lurking in the woods. As the moon reaches its zenith, strange symbols appear, animals vanish, and whispers echo through the trees. A group of researchers must unravel the ritual’s origins before the rising darkness consumes the land.',
    actors: [
      'Mara Siv',
      'Theo Rylan',
      'Isis Crowe',
      'Ronan Dray',
      'Cassia Vale',
      'Elric Thorn',
    ],
  },
  {
    id: 13,
    title: 'Crimson Dawn',
    image: '13.jpg',
    genre: 'fantasy',
    rating: 8.4,
    description:
      "A rising rebellion challenges a tyrant wielding forbidden blood magic. As war engulfs the continent, unlikely heroes emerge—each with their own secrets and reasons to fight. The rebellion's strength hinges on uncovering ancient truths buried beneath centuries of oppression.",
    actors: [
      'Riven Hale',
      'Lyra Crest',
      'Damon Stroud',
      'Selene Wraith',
      'Corin Vale',
      'Talia Frost',
    ],
  },
  {
    id: 14,
    title: 'Silent Kingdom',
    image: '14.jpg',
    genre: 'fantasy',
    rating: 6.5,
    description:
      'A prince without a voice must unite fractured realms before war erupts. Guided by an ancient prophecy and driven by the memory of his fallen family, he journeys through lands filled with magic, treachery, and forgotten gods. Only by reclaiming his strength can he restore peace to a world on the brink.',
    actors: [
      'Corin Vale',
      'Isolde Wynn',
      'Taren Holt',
      'Sylas Dray',
      'Eira Thorn',
      'Jalen Frost',
    ],
  },
  {
    id: 15,
    title: 'Mystic Rite',
    image: '15.jpg',
    genre: 'fantasy',
    rating: 9.8,
    description:
      'An apprentice sorcerer undergoes a deadly trial to safeguard ancient magic. Facing illusions, monsters, and trials of spirit, she discovers the truth about her lineage—and a force bent on claiming the magic for itself. Her journey becomes a struggle not just for power, but for the soul of the world.',
    actors: [
      'Mira Thal',
      'Gareth Sol',
      'Anya Crest',
      'Eron Vale',
      'Saria Wynn',
      'Damon Kael',
    ],
  },
  {
    id: 16,
    title: 'Reign of the Lost',
    image: '16.jpg',
    genre: 'horror',
    rating: 9.1,
    description:
      'A town swallowed by fog hides a monstrous ruler beyond comprehension. When outsiders attempt to uncover the truth, they find themselves trapped in a realm where the fog listens, the shadows wait, and time no longer obeys natural laws. Their only hope lies in unraveling the town’s cursed history.',
    actors: [
      'Silvia Thorn',
      'Jared Knox',
      'Liam Voss',
      'Maren Gage',
      'Torin Vale',
      'Elara Frost',
    ],
  },
  {
    id: 17,
    title: 'Timeless Myth',
    image: '17.jpg',
    genre: 'drama',
    rating: 4.0,
    description:
      'A historian’s discovery of an ancient artifact spirals his life into chaos. As he traces its origins, he becomes entangled in a web of academic rivalry, hidden societies, and secrets powerful enough to upend history itself. The more he uncovers, the more he realizes that some truths were buried for good reason.',
    actors: [
      'Fiona Hale',
      'Owen Crest',
      'Julian Marr',
      'Kira Vance',
      'Elden Rourke',
      'Soren Vale',
    ],
  },
  {
    id: 18,
    title: 'Oath of the Fallen',
    image: '18.jpg',
    genre: 'fantasy',
    rating: 6.3,
    description:
      'A warrior breaks his sacred oath to save a child marked by destiny. Hunted by those he once served, he journeys across untamed lands to protect her from forces that seek to exploit her gift. Each step reveals the cost of his betrayal—and the true power hidden within the child.',
    actors: [
      'Eris Vale',
      'Kaden Stroud',
      'Lysa Thorn',
      'Roran Vex',
      'Mira Solen',
      'Garrick Vale',
    ],
  },
  {
    id: 19,
    title: 'Veil of Night',
    image: '19.jpg',
    genre: 'drama',
    rating: 9.5,
    description:
      'A grieving musician uncovers long‑hidden truths about the night her life changed forever. Through mysterious recordings, cryptic clues, and fragile relationships, she pieces together a story much darker—and more intertwined with her past—than she imagined. Her search for closure becomes a journey of healing, revelation, and rediscovery.',
    actors: [
      'Aria Wynn',
      'Sebastian Crow',
      'Milo Ashen',
      'Elara Frost',
      'Jonas Vale',
      'Cassian Drew',
    ],
  },
  {
    id: 20,
    title: 'Guardians of Twilight',
    image: '20.jpg',
    genre: 'horror',
    rating: 7.4,
    description:
      'When dusk falls, ancient guardians rise to fight an unspeakable evil. As supernatural forces breach the border between worlds, a small group of survivors must join the guardians in a desperate last stand. The fate of both realms hangs in the balance as twilight approaches once more.',
    actors: [
      'Cassia Frost',
      'Roman Vale',
      'Dara Quinn',
      'Nolan Wraith',
      'Sera Dray',
      'Lysander Crow',
    ],
  },
];
